/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as DashboardLayoutImport } from './routes/_dashboardLayout'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as DashboardLayoutDashboardIndexImport } from './routes/_dashboardLayout/dashboard/index'
import { Route as DashboardLayoutCoursesIndexImport } from './routes/_dashboardLayout/courses/index'
import { Route as AuthCallbackProviderIdImport } from './routes/auth.callback.$providerId'
import { Route as DashboardLayoutCoursesCourseSlugImport } from './routes/_dashboardLayout/courses/$courseSlug'
import { Route as DashboardLayoutUserSettingsImport } from './routes/_dashboardLayout/_user/settings'
import { Route as DashboardLayoutUserProfileImport } from './routes/_dashboardLayout/_user/profile'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexImport.update({
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutCoursesIndexRoute =
  DashboardLayoutCoursesIndexImport.update({
    path: '/courses/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const AuthCallbackProviderIdRoute = AuthCallbackProviderIdImport.update({
  path: '/callback/$providerId',
  getParentRoute: () => AuthRoute,
} as any)

const DashboardLayoutCoursesCourseSlugRoute =
  DashboardLayoutCoursesCourseSlugImport.update({
    path: '/courses/$courseSlug',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutUserSettingsRoute =
  DashboardLayoutUserSettingsImport.update({
    path: '/settings',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutUserProfileRoute = DashboardLayoutUserProfileImport.update(
  {
    path: '/profile',
    getParentRoute: () => DashboardLayoutRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_dashboardLayout/_user/profile': {
      id: '/_dashboardLayout/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardLayoutUserProfileImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/_user/settings': {
      id: '/_dashboardLayout/_user/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardLayoutUserSettingsImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/courses/$courseSlug': {
      id: '/_dashboardLayout/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof DashboardLayoutCoursesCourseSlugImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/auth/callback/$providerId': {
      id: '/auth/callback/$providerId'
      path: '/callback/$providerId'
      fullPath: '/auth/callback/$providerId'
      preLoaderRoute: typeof AuthCallbackProviderIdImport
      parentRoute: typeof AuthImport
    }
    '/_dashboardLayout/courses/': {
      id: '/_dashboardLayout/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof DashboardLayoutCoursesIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/dashboard/': {
      id: '/_dashboardLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRoute.addChildren({
    DashboardLayoutUserProfileRoute,
    DashboardLayoutUserSettingsRoute,
    DashboardLayoutCoursesCourseSlugRoute,
    DashboardLayoutCoursesIndexRoute,
    DashboardLayoutDashboardIndexRoute,
  }),
  AuthRoute: AuthRoute.addChildren({
    AuthIndexRoute,
    AuthCallbackProviderIdRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboardLayout",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dashboardLayout": {
      "filePath": "_dashboardLayout.tsx",
      "children": [
        "/_dashboardLayout/_user/profile",
        "/_dashboardLayout/_user/settings",
        "/_dashboardLayout/courses/$courseSlug",
        "/_dashboardLayout/courses/",
        "/_dashboardLayout/dashboard/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/",
        "/auth/callback/$providerId"
      ]
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/_dashboardLayout/_user/profile": {
      "filePath": "_dashboardLayout/_user/profile.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/_user/settings": {
      "filePath": "_dashboardLayout/_user/settings.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/courses/$courseSlug": {
      "filePath": "_dashboardLayout/courses/$courseSlug.tsx",
      "parent": "/_dashboardLayout"
    },
    "/auth/callback/$providerId": {
      "filePath": "auth.callback.$providerId.tsx",
      "parent": "/auth"
    },
    "/_dashboardLayout/courses/": {
      "filePath": "_dashboardLayout/courses/index.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/dashboard/": {
      "filePath": "_dashboardLayout/dashboard/index.tsx",
      "parent": "/_dashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
